//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.DomainModel.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Base_Quantity
    {
        public int QuantityId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> ProdId { get; set; }
    
        public virtual BASE_Location BASE_Location { get; set; }
        public virtual BASE_Product BASE_Product { get; set; }
    }
}
