//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.DomainModel.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE_PricingScheme
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BASE_PricingScheme()
        {
            this.BASE_Customer = new HashSet<BASE_Customer>();
        }
    
        public int PricingSchemeId { get; set; }
        public string Name { get; set; }
        public Nullable<int> LastModUserId { get; set; }
        public Nullable<System.DateTime> LastModDttm { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CurrencyId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BASE_Customer> BASE_Customer { get; set; }
        public virtual GLOBAL_Currency GLOBAL_Currency { get; set; }
        public virtual BASE_User BASE_User { get; set; }
    }
}
