//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.DomainModel.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE_Customer
    {
        public int CustomerId { get; set; }
        public Nullable<int> Version { get; set; }
        public string Name { get; set; }
        public string VendorPermitNumber { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> DefaultPricingSchemeId { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<int> DefaultPaymentTermsId { get; set; }
        public Nullable<int> TaxingSchemeId { get; set; }
        public string DefaultCarrier { get; set; }
        public string DefaultPaymentMethod { get; set; }
        public string ContactName { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
        public string AddressRemarks { get; set; }
        public Nullable<int> AddressType { get; set; }
        public Nullable<bool> UsingBillingAddress { get; set; }
        public string BillingAddress1 { get; set; }
        public string BillingAddress2 { get; set; }
        public string BillingCity { get; set; }
        public string BillingState { get; set; }
        public string BillingCountry { get; set; }
        public string BillingPostalCode { get; set; }
        public string BillingAddressRemarks { get; set; }
        public Nullable<int> BillingAddressType { get; set; }
        public Nullable<bool> UsingShippingAddress { get; set; }
        public string ShippingAddress1 { get; set; }
        public string ShippingAddress2 { get; set; }
        public string ShippingCity { get; set; }
        public string ShippingState { get; set; }
        public string ShippingCountry { get; set; }
        public string ShippingPostalCode { get; set; }
        public string ShippingAddressRemarks { get; set; }
        public Nullable<int> ShippingAddressType { get; set; }
        public string CCardType { get; set; }
        public string CCardNum { get; set; }
        public string CCardSecurityNum { get; set; }
        public string CCardExpDate { get; set; }
        public Nullable<int> LastModUserId { get; set; }
        public Nullable<System.DateTime> LastModDttm { get; set; }
        public byte[] Timestamp { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Website { get; set; }
        public string DefaultSalesRep { get; set; }
        public Nullable<int> DefaultLocationId { get; set; }
    
        public virtual BASE_Location BASE_Location { get; set; }
        public virtual BASE_TaxingScheme BASE_TaxingScheme { get; set; }
        public virtual BASE_PaymentTerms BASE_PaymentTerms { get; set; }
        public virtual BASE_PricingScheme BASE_PricingScheme { get; set; }
        public virtual BASE_User BASE_User { get; set; }
    }
}
