//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.DomainModel.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE_City
    {
        public int CityId { get; set; }
        public string CityName { get; set; }
        public Nullable<int> FKStateId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual BASE_State BASE_State { get; set; }
    }
}
