//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.DomainModel.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE_Location
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BASE_Location()
        {
            this.BASE_Customer = new HashSet<BASE_Customer>();
            this.Base_Quantity = new HashSet<Base_Quantity>();
            this.PO_PurchaseOrder = new HashSet<PO_PurchaseOrder>();
            this.PO_PurchaseOrderReceive_Line = new HashSet<PO_PurchaseOrderReceive_Line>();
            this.PO_PurchaseOrderUnstock_Line = new HashSet<PO_PurchaseOrderUnstock_Line>();
            this.SO_SalesOrderPick_Line = new HashSet<SO_SalesOrderPick_Line>();
            this.SO_SalesOrderRestock_Line = new HashSet<SO_SalesOrderRestock_Line>();
        }
    
        public int LocationId { get; set; }
        public string Name { get; set; }
        public Nullable<int> LastModUserId { get; set; }
        public Nullable<System.DateTime> LastModDttm { get; set; }
        public byte[] Timestamp { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BASE_Customer> BASE_Customer { get; set; }
        public virtual BASE_User BASE_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Base_Quantity> Base_Quantity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PO_PurchaseOrder> PO_PurchaseOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PO_PurchaseOrderReceive_Line> PO_PurchaseOrderReceive_Line { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PO_PurchaseOrderUnstock_Line> PO_PurchaseOrderUnstock_Line { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SO_SalesOrderPick_Line> SO_SalesOrderPick_Line { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SO_SalesOrderRestock_Line> SO_SalesOrderRestock_Line { get; set; }
    }
}
