//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.DomainModel.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE_TaxingScheme
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BASE_TaxingScheme()
        {
            this.BASE_Customer = new HashSet<BASE_Customer>();
            this.PO_PurchaseOrder = new HashSet<PO_PurchaseOrder>();
        }
    
        public int TaxingSchemeId { get; set; }
        public string Name { get; set; }
        public string Tax1Name { get; set; }
        public string Tax2Name { get; set; }
        public Nullable<bool> CalculateTax2OnTax1 { get; set; }
        public Nullable<int> LastModUserId { get; set; }
        public Nullable<System.DateTime> LastModDttm { get; set; }
        public byte[] Timestamp { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> Tax1OnShipping { get; set; }
        public Nullable<int> DefaultTaxCodeId { get; set; }
        public Nullable<bool> Tax2OnShipping { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BASE_Customer> BASE_Customer { get; set; }
        public virtual BASE_TaxCode BASE_TaxCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PO_PurchaseOrder> PO_PurchaseOrder { get; set; }
    }
}
