//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.DomainModel.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BASE_Product()
        {
            this.Base_BillOfMaterials = new HashSet<Base_BillOfMaterials>();
            this.BASE_ItemPrice = new HashSet<BASE_ItemPrice>();
            this.Base_Quantity = new HashSet<Base_Quantity>();
            this.DUMMY_ReorderStock_Line = new HashSet<DUMMY_ReorderStock_Line>();
            this.PO_PurchaseOrder_Line = new HashSet<PO_PurchaseOrder_Line>();
            this.PO_PurchaseOrderReceive_Line = new HashSet<PO_PurchaseOrderReceive_Line>();
            this.PO_PurchaseOrderReturn_Line = new HashSet<PO_PurchaseOrderReturn_Line>();
            this.PO_PurchaseOrderUnstock_Line = new HashSet<PO_PurchaseOrderUnstock_Line>();
            this.SO_SalesOrder_Line = new HashSet<SO_SalesOrder_Line>();
            this.SO_SalesOrderPack_Line = new HashSet<SO_SalesOrderPack_Line>();
            this.SO_SalesOrderPick_Line = new HashSet<SO_SalesOrderPick_Line>();
            this.SO_SalesOrderRestock_Line = new HashSet<SO_SalesOrderRestock_Line>();
            this.SO_SalesOrderReturn_Line = new HashSet<SO_SalesOrderReturn_Line>();
        }
    
        public Nullable<int> Version { get; set; }
        public Nullable<int> ItemType { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Remarks { get; set; }
        public string BarCode { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string DefaultLocationId { get; set; }
        public string DefaultSublocation { get; set; }
        public Nullable<decimal> ReorderPoint { get; set; }
        public Nullable<decimal> ReorderQuantity { get; set; }
        public string Uom { get; set; }
        public Nullable<decimal> MasterPackQty { get; set; }
        public Nullable<decimal> InnerPackQty { get; set; }
        public Nullable<decimal> CaseLength { get; set; }
        public Nullable<decimal> CaseWidth { get; set; }
        public Nullable<decimal> CaseHeight { get; set; }
        public Nullable<decimal> CaseWeight { get; set; }
        public Nullable<decimal> ProductLength { get; set; }
        public Nullable<decimal> ProductWidth { get; set; }
        public Nullable<decimal> ProductHeight { get; set; }
        public Nullable<decimal> ProductWeight { get; set; }
        public Nullable<int> LastVendorId { get; set; }
        public Nullable<bool> IsSellable { get; set; }
        public Nullable<bool> IsPurchaseable { get; set; }
        public Nullable<System.DateTime> DateIntroduced { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public Nullable<int> LastModUserId { get; set; }
        public Nullable<System.DateTime> LastModDttm { get; set; }
        public byte[] Timestamp { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string PictureFileAttachmentId { get; set; }
        public string SoUomName { get; set; }
        public Nullable<decimal> SoUomRatioStd { get; set; }
        public Nullable<decimal> SoUomRatio { get; set; }
        public string PoUomName { get; set; }
        public Nullable<decimal> PoUomRatioStd { get; set; }
        public Nullable<decimal> PoUomRatio { get; set; }
        public int ProdId { get; set; }
        public Nullable<bool> TrackSerials { get; set; }
        public Nullable<decimal> ProductCost { get; set; }
        public Nullable<decimal> NormalPrice { get; set; }
    
        public virtual ACC_ProductDefaultCost ACC_ProductDefaultCost { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Base_BillOfMaterials> Base_BillOfMaterials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BASE_ItemPrice> BASE_ItemPrice { get; set; }
        public virtual BASE_User BASE_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Base_Quantity> Base_Quantity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DUMMY_ReorderStock_Line> DUMMY_ReorderStock_Line { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PO_PurchaseOrder_Line> PO_PurchaseOrder_Line { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PO_PurchaseOrderReceive_Line> PO_PurchaseOrderReceive_Line { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PO_PurchaseOrderReturn_Line> PO_PurchaseOrderReturn_Line { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PO_PurchaseOrderUnstock_Line> PO_PurchaseOrderUnstock_Line { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SO_SalesOrder_Line> SO_SalesOrder_Line { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SO_SalesOrderPack_Line> SO_SalesOrderPack_Line { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SO_SalesOrderPick_Line> SO_SalesOrderPick_Line { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SO_SalesOrderRestock_Line> SO_SalesOrderRestock_Line { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SO_SalesOrderReturn_Line> SO_SalesOrderReturn_Line { get; set; }
    }
}
