//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.DomainModel.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE_TaxCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BASE_TaxCode()
        {
            this.BASE_TaxingScheme = new HashSet<BASE_TaxingScheme>();
            this.PO_PurchaseOrder_Line = new HashSet<PO_PurchaseOrder_Line>();
            this.PO_PurchaseOrderReturn_Line = new HashSet<PO_PurchaseOrderReturn_Line>();
            this.SO_SalesOrder_Line = new HashSet<SO_SalesOrder_Line>();
            this.SO_SalesOrderReturn_Line = new HashSet<SO_SalesOrderReturn_Line>();
        }
    
        public int TaxCodeId { get; set; }
        public Nullable<int> TaxingSchemeId { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Tax1Rate { get; set; }
        public Nullable<decimal> Tax2Rate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> LastModUserId { get; set; }
        public Nullable<System.DateTime> LastModDttm { get; set; }
        public byte[] Timestamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BASE_TaxingScheme> BASE_TaxingScheme { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PO_PurchaseOrder_Line> PO_PurchaseOrder_Line { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PO_PurchaseOrderReturn_Line> PO_PurchaseOrderReturn_Line { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SO_SalesOrder_Line> SO_SalesOrder_Line { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SO_SalesOrderReturn_Line> SO_SalesOrderReturn_Line { get; set; }
    }
}
