//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.DomainModel.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE_ItemPrice
    {
        public int ItemPriceId { get; set; }
        public int PricingSchemeId { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> LastModUserId { get; set; }
        public Nullable<System.DateTime> LastModDttm { get; set; }
        public Nullable<int> ProdId { get; set; }
        public Nullable<decimal> NormalPrice { get; set; }
    
        public virtual BASE_Product BASE_Product { get; set; }
    }
}
