//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.DomainModel.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUMMY_ReorderStock_Line
    {
        public int ReorderStockLineId { get; set; }
        public int ReorderStockId { get; set; }
        public string Description { get; set; }
        public decimal QuantityOwned { get; set; }
        public Nullable<decimal> ReorderPoint { get; set; }
        public decimal ReorderQuantity { get; set; }
        public int VendorId { get; set; }
        public byte[] Timestamp { get; set; }
        public decimal QuantityOnOrder { get; set; }
        public decimal QuantityPending { get; set; }
        public int ProdId { get; set; }
    
        public virtual BASE_Product BASE_Product { get; set; }
    }
}
