//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.DomainModel.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLOBAL_Currency
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GLOBAL_Currency()
        {
            this.BASE_PricingScheme = new HashSet<BASE_PricingScheme>();
            this.BASE_Vendor = new HashSet<BASE_Vendor>();
            this.PO_PurchaseOrder = new HashSet<PO_PurchaseOrder>();
        }
    
        public int CurrencyId { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string Symbol { get; set; }
        public byte[] Timestamp { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<short> DecimalPlaces { get; set; }
        public string DecimalSeparator { get; set; }
        public string ThousandsSeparator { get; set; }
        public Nullable<short> CRCurrencyPositionType { get; set; }
        public Nullable<short> CRNegativeType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BASE_PricingScheme> BASE_PricingScheme { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BASE_Vendor> BASE_Vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PO_PurchaseOrder> PO_PurchaseOrder { get; set; }
    }
}
