//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.DomainModel.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_StockAdjustment_Line
    {
        public int StockAdjustmentLineId { get; set; }
        public int StockAdjustmentId { get; set; }
        public Nullable<int> Version { get; set; }
        public Nullable<int> ProdId { get; set; }
        public string Description { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string Sublocation { get; set; }
        public Nullable<decimal> QuantityBefore { get; set; }
        public string QuantityBeforeUom { get; set; }
        public Nullable<decimal> QuantityBeforeDisplay { get; set; }
        public Nullable<decimal> QuantityAfter { get; set; }
        public string QuantityAfterUom { get; set; }
        public Nullable<decimal> QuantityAfterDisplay { get; set; }
        public Nullable<decimal> Difference { get; set; }
        public string DifferenceUom { get; set; }
        public Nullable<decimal> DifferenceDisplay { get; set; }
        public byte[] Timestamp { get; set; }
        public string Serials { get; set; }
    }
}
