//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.DomainModel.DatabaseModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InventoryEntities : DbContext
    {
        public InventoryEntities()
            : base("name=InventoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACC_ProductDefaultCost> ACC_ProductDefaultCost { get; set; }
        public virtual DbSet<Base_BillOfMaterials> Base_BillOfMaterials { get; set; }
        public virtual DbSet<Base_Carrier> Base_Carrier { get; set; }
        public virtual DbSet<BASE_Category> BASE_Category { get; set; }
        public virtual DbSet<BASE_City> BASE_City { get; set; }
        public virtual DbSet<BASE_Country> BASE_Country { get; set; }
        public virtual DbSet<BASE_Customer> BASE_Customer { get; set; }
        public virtual DbSet<BASE_ItemPrice> BASE_ItemPrice { get; set; }
        public virtual DbSet<BASE_Location> BASE_Location { get; set; }
        public virtual DbSet<BASE_PaymentMethod> BASE_PaymentMethod { get; set; }
        public virtual DbSet<BASE_PaymentTerms> BASE_PaymentTerms { get; set; }
        public virtual DbSet<BASE_PricingScheme> BASE_PricingScheme { get; set; }
        public virtual DbSet<BASE_Product> BASE_Product { get; set; }
        public virtual DbSet<Base_Quantity> Base_Quantity { get; set; }
        public virtual DbSet<BASE_ReceivingAddress> BASE_ReceivingAddress { get; set; }
        public virtual DbSet<Base_SalesRep> Base_SalesRep { get; set; }
        public virtual DbSet<BASE_State> BASE_State { get; set; }
        public virtual DbSet<BASE_TaxCode> BASE_TaxCode { get; set; }
        public virtual DbSet<BASE_TaxingScheme> BASE_TaxingScheme { get; set; }
        public virtual DbSet<Base_Unit> Base_Unit { get; set; }
        public virtual DbSet<BASE_User> BASE_User { get; set; }
        public virtual DbSet<BASE_Vendor> BASE_Vendor { get; set; }
        public virtual DbSet<BASE_VendorItem> BASE_VendorItem { get; set; }
        public virtual DbSet<DUMMY_ReorderStock_Line> DUMMY_ReorderStock_Line { get; set; }
        public virtual DbSet<GLOBAL_Currency> GLOBAL_Currency { get; set; }
        public virtual DbSet<INV_StockAdjustment> INV_StockAdjustment { get; set; }
        public virtual DbSet<INV_StockAdjustment_Line> INV_StockAdjustment_Line { get; set; }
        public virtual DbSet<PO_InventoryStatus> PO_InventoryStatus { get; set; }
        public virtual DbSet<PO_PaymentStatus> PO_PaymentStatus { get; set; }
        public virtual DbSet<PO_PurchaseOrder> PO_PurchaseOrder { get; set; }
        public virtual DbSet<PO_PurchaseOrder_Line> PO_PurchaseOrder_Line { get; set; }
        public virtual DbSet<PO_PurchaseOrder_Version> PO_PurchaseOrder_Version { get; set; }
        public virtual DbSet<PO_PurchaseOrderReceive_Line> PO_PurchaseOrderReceive_Line { get; set; }
        public virtual DbSet<PO_PurchaseOrderReturn_Line> PO_PurchaseOrderReturn_Line { get; set; }
        public virtual DbSet<PO_PurchaseOrderUnstock_Line> PO_PurchaseOrderUnstock_Line { get; set; }
        public virtual DbSet<PO_Status> PO_Status { get; set; }
        public virtual DbSet<SO_SalesOrder> SO_SalesOrder { get; set; }
        public virtual DbSet<SO_SalesOrder_Line> SO_SalesOrder_Line { get; set; }
        public virtual DbSet<SO_SalesOrder_Line_Version> SO_SalesOrder_Line_Version { get; set; }
        public virtual DbSet<SO_SalesOrder_Version> SO_SalesOrder_Version { get; set; }
        public virtual DbSet<SO_SalesOrderAttachment> SO_SalesOrderAttachment { get; set; }
        public virtual DbSet<SO_SalesOrderPack_Line> SO_SalesOrderPack_Line { get; set; }
        public virtual DbSet<SO_SalesOrderPack_Line_Version> SO_SalesOrderPack_Line_Version { get; set; }
        public virtual DbSet<SO_SalesOrderPaymentHistory_Line> SO_SalesOrderPaymentHistory_Line { get; set; }
        public virtual DbSet<SO_SalesOrderPaymentHistory_Line_Version> SO_SalesOrderPaymentHistory_Line_Version { get; set; }
        public virtual DbSet<SO_SalesOrderPick_Line> SO_SalesOrderPick_Line { get; set; }
        public virtual DbSet<SO_SalesOrderPick_Line_Version> SO_SalesOrderPick_Line_Version { get; set; }
        public virtual DbSet<SO_SalesOrderRestock_Line> SO_SalesOrderRestock_Line { get; set; }
        public virtual DbSet<SO_SalesOrderRestock_Line_Version> SO_SalesOrderRestock_Line_Version { get; set; }
        public virtual DbSet<SO_SalesOrderReturn_Line> SO_SalesOrderReturn_Line { get; set; }
        public virtual DbSet<SO_SalesOrderReturn_Line_Version> SO_SalesOrderReturn_Line_Version { get; set; }
        public virtual DbSet<SO_SalesOrderShip_Line> SO_SalesOrderShip_Line { get; set; }
        public virtual DbSet<SO_SalesOrderShip_Line_Version> SO_SalesOrderShip_Line_Version { get; set; }
        public virtual DbSet<SO_SalesOrderShipContainer> SO_SalesOrderShipContainer { get; set; }
        public virtual DbSet<SO_SalesOrderShipContainer_Version> SO_SalesOrderShipContainer_Version { get; set; }
        public virtual DbSet<SO_SalesOrderSticky> SO_SalesOrderSticky { get; set; }
        public virtual DbSet<SO_SalesOrderSticky_Version> SO_SalesOrderSticky_Version { get; set; }
        public virtual DbSet<tblInventory> tblInventories { get; set; }
        public virtual DbSet<tblPaymentHistory> tblPaymentHistories { get; set; }
    }
}
