//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.DomainModel.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PO_PurchaseOrderReceive_Line
    {
        public int PurchaseOrderReceiveLineId { get; set; }
        public int PurchaseOrderId { get; set; }
        public Nullable<int> Version { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public string Description { get; set; }
        public string VendorItemCode { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string Sublocation { get; set; }
        public byte[] Timestamp { get; set; }
        public string QuantityUom { get; set; }
        public Nullable<decimal> QuantityDisplay { get; set; }
        public Nullable<int> ProdId { get; set; }
        public Nullable<int> LineNum { get; set; }
        public string Serials { get; set; }
        public Nullable<int> VendorItemCodeId { get; set; }
        public Nullable<int> PurchaseOrderLineId { get; set; }
    
        public virtual BASE_Location BASE_Location { get; set; }
        public virtual BASE_Product BASE_Product { get; set; }
        public virtual PO_PurchaseOrder PO_PurchaseOrder { get; set; }
    }
}
