//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.DomainModel.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PO_PurchaseOrder_Version
    {
        public int PurchaseOrderVersionId { get; set; }
        public int PurchaseOrderId { get; set; }
        public int Version { get; set; }
        public string OrderNumber { get; set; }
        public string VendorOrderNumber { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int VendorId { get; set; }
        public Nullable<int> PaymentTermsId { get; set; }
        public string Carrier { get; set; }
        public string ContactName { get; set; }
        public string Phone { get; set; }
        public string VendorAddress1 { get; set; }
        public string VendorAddress2 { get; set; }
        public string VendorCity { get; set; }
        public string VendorState { get; set; }
        public string VendorCountry { get; set; }
        public string VendorPostalCode { get; set; }
        public string VendorAddressRemarks { get; set; }
        public Nullable<int> VendorAddressType { get; set; }
        public string ShipToAddress1 { get; set; }
        public string ShipToAddress2 { get; set; }
        public string ShipToCity { get; set; }
        public string ShipToState { get; set; }
        public string ShipToCountry { get; set; }
        public string ShipToPostalCode { get; set; }
        public string ShipToAddressRemarks { get; set; }
        public Nullable<int> ShipToAddressType { get; set; }
        public Nullable<System.DateTime> RequestShipDate { get; set; }
        public int TaxingSchemeId { get; set; }
        public string OrderRemarks { get; set; }
        public decimal OrderSubTotal { get; set; }
        public decimal OrderTax1 { get; set; }
        public decimal OrderTax2 { get; set; }
        public Nullable<decimal> OrderExtra { get; set; }
        public decimal OrderTotal { get; set; }
        public Nullable<decimal> Tax1Rate { get; set; }
        public Nullable<decimal> Tax2Rate { get; set; }
        public bool CalculateTax2OnTax1 { get; set; }
        public string Tax1Name { get; set; }
        public string Tax2Name { get; set; }
        public string ReceiveRemarks { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public decimal AmountPaid { get; set; }
        public decimal Balance { get; set; }
        public string ReturnRemarks { get; set; }
        public decimal ReturnSubTotal { get; set; }
        public Nullable<decimal> ReturnTax1 { get; set; }
        public decimal ReturnTax2 { get; set; }
        public Nullable<decimal> ReturnExtra { get; set; }
        public decimal ReturnTotal { get; set; }
        public decimal ReturnFee { get; set; }
        public string UnstockRemarks { get; set; }
        public string Custom2 { get; set; }
        public string Custom1 { get; set; }
        public string Custom3 { get; set; }
        public string Custom4 { get; set; }
        public string Custom5 { get; set; }
        public int LastModUserId { get; set; }
        public System.DateTime LastModDttm { get; set; }
        public byte[] Timestamp { get; set; }
        public bool Tax1OnShipping { get; set; }
        public Nullable<decimal> AncillaryExpenses { get; set; }
        public bool AncillaryIsPercent { get; set; }
        public Nullable<int> LocationId { get; set; }
        public bool ShowShipping { get; set; }
        public string ShipToCompanyName { get; set; }
        public int CurrencyId { get; set; }
        public decimal ExchangeRate { get; set; }
        public bool Tax2OnShipping { get; set; }
        public string SummaryLinePermutation { get; set; }
        public decimal Total { get; set; }
        public int PaymentStatus { get; set; }
        public int InventoryStatus { get; set; }
        public bool IsCancelled { get; set; }
        public bool IsCompleted { get; set; }
    }
}
