//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.DomainModel.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PO_PurchaseOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PO_PurchaseOrder()
        {
            this.PO_PurchaseOrder_Line = new HashSet<PO_PurchaseOrder_Line>();
            this.PO_PurchaseOrderReceive_Line = new HashSet<PO_PurchaseOrderReceive_Line>();
            this.PO_PurchaseOrderReturn_Line = new HashSet<PO_PurchaseOrderReturn_Line>();
            this.PO_PurchaseOrderUnstock_Line = new HashSet<PO_PurchaseOrderUnstock_Line>();
        }
    
        public int PurchaseOrderId { get; set; }
        public Nullable<int> Version { get; set; }
        public string OrderNumber { get; set; }
        public string VendorOrderNumber { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> VendorId { get; set; }
        public Nullable<int> PaymentTermsId { get; set; }
        public string Carrier { get; set; }
        public string ContactName { get; set; }
        public string Phone { get; set; }
        public string VendorAddress1 { get; set; }
        public string VendorAddress2 { get; set; }
        public string VendorCity { get; set; }
        public string VendorState { get; set; }
        public string VendorCountry { get; set; }
        public string VendorPostalCode { get; set; }
        public string VendorAddressRemarks { get; set; }
        public Nullable<int> VendorAddressType { get; set; }
        public string ShipToAddress1 { get; set; }
        public string ShipToAddress2 { get; set; }
        public string ShipToCity { get; set; }
        public string ShipToState { get; set; }
        public string ShipToCountry { get; set; }
        public string ShipToPostalCode { get; set; }
        public string ShipToAddressRemarks { get; set; }
        public Nullable<int> ShipToAddressType { get; set; }
        public Nullable<System.DateTime> RequestShipDate { get; set; }
        public Nullable<int> TaxingSchemeId { get; set; }
        public string OrderRemarks { get; set; }
        public Nullable<decimal> OrderSubTotal { get; set; }
        public Nullable<decimal> OrderTax1 { get; set; }
        public Nullable<decimal> OrderTax2 { get; set; }
        public Nullable<decimal> OrderExtra { get; set; }
        public Nullable<decimal> OrderTotal { get; set; }
        public Nullable<decimal> Tax1Rate { get; set; }
        public Nullable<decimal> Tax2Rate { get; set; }
        public Nullable<bool> CalculateTax2OnTax1 { get; set; }
        public string Tax1Name { get; set; }
        public string Tax2Name { get; set; }
        public string ReceiveRemarks { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string ReturnRemarks { get; set; }
        public Nullable<decimal> ReturnSubTotal { get; set; }
        public Nullable<decimal> ReturnTax1 { get; set; }
        public Nullable<decimal> ReturnTax2 { get; set; }
        public Nullable<decimal> ReturnExtra { get; set; }
        public Nullable<decimal> ReturnTotal { get; set; }
        public Nullable<decimal> ReturnFee { get; set; }
        public string UnstockRemarks { get; set; }
        public Nullable<int> LastModUserId { get; set; }
        public Nullable<System.DateTime> LastModDttm { get; set; }
        public byte[] Timestamp { get; set; }
        public Nullable<bool> Tax1OnShipping { get; set; }
        public Nullable<decimal> AncillaryExpenses { get; set; }
        public Nullable<bool> AncillaryIsPercent { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<bool> ShowShipping { get; set; }
        public string ShipToCompanyName { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<bool> Tax2OnShipping { get; set; }
        public string SummaryLinePermutation { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> PaymentStatus { get; set; }
        public Nullable<int> InventoryStatus { get; set; }
        public Nullable<bool> IsCancelled { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public Nullable<decimal> Freight { get; set; }
        public Nullable<int> TotalOrder { get; set; }
        public Nullable<int> TotalReceived { get; set; }
        public Nullable<decimal> ReturnAmount { get; set; }
    
        public virtual BASE_Location BASE_Location { get; set; }
        public virtual BASE_PaymentTerms BASE_PaymentTerms { get; set; }
        public virtual BASE_TaxingScheme BASE_TaxingScheme { get; set; }
        public virtual BASE_User BASE_User { get; set; }
        public virtual GLOBAL_Currency GLOBAL_Currency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PO_PurchaseOrder_Line> PO_PurchaseOrder_Line { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PO_PurchaseOrderReceive_Line> PO_PurchaseOrderReceive_Line { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PO_PurchaseOrderReturn_Line> PO_PurchaseOrderReturn_Line { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PO_PurchaseOrderUnstock_Line> PO_PurchaseOrderUnstock_Line { get; set; }
    }
}
