//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.DomainModel.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SO_SalesOrder_Line_Version
    {
        public int SalesOrderVersionLineId { get; set; }
        public int SalesOrderLineId { get; set; }
        public int SalesOrderId { get; set; }
        public Nullable<int> Version { get; set; }
        public Nullable<int> LineNum { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public byte[] Timestamp { get; set; }
        public string QuantityUom { get; set; }
        public Nullable<decimal> QuantityDisplay { get; set; }
        public Nullable<bool> DiscountIsPercent { get; set; }
        public Nullable<int> ProdId { get; set; }
        public Nullable<int> TaxCodeId { get; set; }
        public Nullable<decimal> Tax1Rate { get; set; }
        public Nullable<decimal> Tax2Rate { get; set; }
        public Nullable<bool> ServiceCompleted { get; set; }
        public string Serials { get; set; }
    }
}
