//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.DomainModel.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SO_SalesOrderShip_Line_Version
    {
        public int SalesOrderShipVersionLineId { get; set; }
        public int SalesOrderShipLineId { get; set; }
        public int SalesOrderId { get; set; }
        public Nullable<int> Version { get; set; }
        public Nullable<int> LineNum { get; set; }
        public Nullable<System.DateTime> ShippedDate { get; set; }
        public string Carrier { get; set; }
        public string TrackingNumber { get; set; }
        public string Description { get; set; }
        public byte[] Timestamp { get; set; }
    }
}
