//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.DomainModel.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SO_SalesOrderShipContainer
    {
        public int SalesOrderShipContainerId { get; set; }
        public int Version { get; set; }
        public Nullable<int> SalesOrderShipLineId { get; set; }
        public string ContainerNumber { get; set; }
        public byte[] Timestamp { get; set; }
    
        public virtual SO_SalesOrderShip_Line SO_SalesOrderShip_Line { get; set; }
    }
}
