//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.DomainModel.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SO_SalesOrderAttachment
    {
        public int SalesOrderAttachmentId { get; set; }
        public int SalesOrderId { get; set; }
        public Nullable<int> FileAttachmentId { get; set; }
        public byte[] Timestamp { get; set; }
    
        public virtual SO_SalesOrder SO_SalesOrder { get; set; }
    }
}
