//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.DomainModel.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SO_SalesOrderShip_Line
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SO_SalesOrderShip_Line()
        {
            this.SO_SalesOrderShipContainer = new HashSet<SO_SalesOrderShipContainer>();
        }
    
        public int SalesOrderShipLineId { get; set; }
        public int SalesOrderId { get; set; }
        public Nullable<int> Version { get; set; }
        public Nullable<int> LineNum { get; set; }
        public Nullable<System.DateTime> ShippedDate { get; set; }
        public string Carrier { get; set; }
        public string TrackingNumber { get; set; }
        public string Description { get; set; }
        public byte[] Timestamp { get; set; }
    
        public virtual SO_SalesOrder SO_SalesOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SO_SalesOrderShipContainer> SO_SalesOrderShipContainer { get; set; }
    }
}
