//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.DomainModel.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPaymentHistory
    {
        public int PaymentHistoryId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> CreditBalance { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> Transactions { get; set; }
        public Nullable<int> vendorID { get; set; }
    
        public virtual BASE_Vendor BASE_Vendor { get; set; }
    }
}
